### ISSUE TITLE
Gista --private does not work correctly.

### ISSUE THREAD

**Issue by lambdalisue** [lambdalisue/vim-gista#41]

**Comment by uri** [comment]
I'm experiencing this too. I tried `Gista -p` and `Gista --private` both created public gists.

**Comment by uri** [comment]
Setting `let g:gista#post_private = 1` then using `Gista` worked for me. You can still use `Gista -P` for public gists.

**Comment by lambdalisue** [comment]
> Setting g:gista#post_private then using Gista worked for me. You can still use Gista -P for public gists.

Ha! I didn't even know this behavior. Thanks :+1:
