### ISSUE TITLE
<c-l> doesn't update gist list

### ISSUE THREAD

**Issue by albertnetymk** [lambdalisue/vim-gista#45]
`Gista -l` shows my `gista:list` buffer, but with my cursor in that buffer, hitting `<c-l>` has no effect at all. I wonder if it's captured by my terminal (iterm2), for it's the same shortcut of clear the screen in the terminal.

**Comment by lambdalisue** [comment]
Well what happen if you hit `<C-l><C-l>` while `<C-l>` stands for refreshing the buffer **without cache**.

**Comment by albertnetymk** [comment]
Sorry for the false alarm. It's working as expected. I guess I was a bit in a hurry when opening this issue; it takes ~ 1 second to have some feedback on the status line of vim (`Requesting gists ...`).

I think you meant `<c-l><c-l>` for refreshing without cache.

Thank you for this useful plugin.
