### ISSUE TITLE
Make harder to publish something by accident

### ISSUE THREAD

**Issue by suy** [lambdalisue/vim-gista#46]
Hi.

I just installed gista, and I accidentally published something I did not want to publish. I opened vim, and the startify.vim buffer appeared. I run :Gista for the first time, but I wanted to do :Gista --list instead. I tried to cancel pressing Ctrl+C and not entering any information in the prompts, but I ended up publishing anonymously the current buffer, which contains the list of recently opened files and repositories that I had, which leaked a bit of private information. Since it is posted anonymously, I can't delete it. Is nothing critical, and doesn't seem to be reachable without the URL, but still a bit it could be problematic.

I'll try to be more careful the next time, but I would not mind something to make mistakes like this harder. Specially for publishing all the opened buffers. Maybe making :Gista (with no arguments) list instead of post a gist by default, or with an option to force the user to confirm before publishing.

Besides that, the plugin looks awesome. Thank you. :)

**Comment by lambdalisue** [comment]
True. Well while ArgumentPapser used in gista improved a lot in vim-gita, I would like to drop backward compatibility and make new one so at that time, I'll fix it up as your suggestion
