### ISSUE TITLE
Problem when reusing the personal access token name

### ISSUE THREAD

**Issue by suy** [lambdalisue/vim-gista#47]
Hello again. Try the following:

1. Log in if not already logged in.
2. Change `g:gista#directory` to a new directory, or remove/rename the current gista directory (so the plugin doesn't see the tokens.json).
3. Try to log in again.

This fails because gista tries to create a token named `vim-gista@hostname`, but there is already one. I think that Gist.vim doesn't have this problem because it uses a name `Gist.vim on hostname 2015/11/20-19:16:33`. Could vim-gista do the same, or is there a different problem?

Thank you!

**Comment by suy** [comment]
Just to clarify: after the log in failure, going to Github and renaming/removing the `vim-gista@hostname` token it works again, of course, but the error message is not clear to someone who doesn't know how it works.

**Comment by lambdalisue** [comment]
Well I prefer to make an error message better because Gist.vim would make too many entry points. So I will fix the message

**Comment by lambdalisue** [comment]
Ok I changed mind. It was so annoying (I just had same issue on my computer and too lazy to access and remove the token from GitHub). I will fix it as your suggestion.

**Comment by suy** [comment]
Good, thank you! :)
