### ISSUE TITLE
:Gista login respond HTTP502 Bad Gateway

### ISSUE THREAD

**Issue by hokorobi** [lambdalisue/vim-gista#50]
db108a1d54 において
:Gista login --apiname=GitHub --username=hokorobi を実行してパスワードを入力すると、
（おそらく）タイムアウト後に以下のようなメッセージが表示されてログイン出来ませんでした。

![dib bitmap](https://cloud.githubusercontent.com/assets/99910/12293340/322c47b4-ba36-11e5-95f5-7659a0530482.png)

何かおかしそうなところがあれば情報をいただけると助かります。

Windows7 kaoriya Vim 7.4.1016 (2016/01/01版) 64bit
curl 7.43.0 (x86_64-pc-msys) libcurl/7.43.0 OpenSSL/1.0.2d zlib/1.2.8 libidn/1.31 libssh2/1.6.0

**Comment by toshi32tony3** [comment]
私の環境でも再現しました。

* Environment Information
 * OS: Windows 7 32-bit
 * Vim version: GVim 7.4.1016

エラーメッセージの内容はhokorobiさんと同様です。
一応、pythonは使える環境です。has('python')すると1が返ってきます。

**Comment by toshi32tony3** [comment]
すみません、Requirementsのwgetが入っていませんでした。入れて再現するか確認してから、また報告します。

**Comment by lambdalisue** [comment]
なるほど、うーん Windows 限定で `python` クライアントでのログインができないのかもしれません。
Windows の場合は強制的に `curl` か `wget` を利用するようにしてみたので [fix/authorize_HTTP502_in_Windows](https://github.com/lambdalisue/vim-gista/tree/fix/authorize_HTTP502_in_Windows) ブランチを試してみていただけませんか？

**Comment by hokorobi** [comment]
fix/authorize_HTTP502_in_Windows でも同じ結果でした。

私の場合はおそらく curl を使っています。
curl を PATH から外すとエラーが表示されるので。
curl を外して wget を入れてもエラーになります。
なぜそうなるのかはわかっていません。

**Comment by toshi32tony3** [comment]
fix/authorize_HTTP502_in_Windowsで、
curlのみ、wgetのみパス通した状態で試してみましたが同じ結果になってしまいました。

**Comment by hokorobi** [comment]
curl から直接 gista が実行しているコマンドを叩いてみようと思うのですが、
コマンドを教えていただけませんか？ > @lambdalisue

**Comment by lambdalisue** [comment]
@hokorobi コマンドを `echomsg` するようにしてみました。チェックアウト後に `:Gista login` を行って見てください。なおパスワードが echo されるはずなので、結果を貼り付ける場合などは気をつけてください

**Comment by lambdalisue** [comment]
http://lingr.com/room/vim/archives/2016/01/14#message-22938744

**Comment by lambdalisue** [comment]
Note: v1 では https://github.com/lambdalisue/vim-gista/blob/d748d3c3281d7e9af171416eedf45c460b0976fa/autoload/gista/gist/raw.vim#L98-L102 のようにしていた。本来は Vital.HTTP の `username` と `password` を利用するべきだと思い修正したんだけど・・・

**Comment by lambdalisue** [comment]
Windows 版 curl のバグ感

1. `authMethod` が指定されている場合 `python` クライアントが利用されない https://github.com/vim-jp/vital.vim/blob/master/autoload/vital/__latest__/Web/HTTP.vim#L291

2. `authMethod` が指定されている場合 `wget` クライアントが利用されない https://github.com/vim-jp/vital.vim/blob/master/autoload/vital/__latest__/Web/HTTP.vim#L567

上記からBASIC認証でも必ず `curl` が利用されるようになっていた模様。

**Comment by lambdalisue** [comment]
https://github.com/mattn/gist-vim/blob/master/autoload/gist.vim#L943

`Content-Type: application/json` が必要感

**Comment by lambdalisue** [comment]
直接の原因は http://lingr.com/room/vim/archives/2016/01/14#message-22939185 のようですが、デフォルトの状態でも動くようにしたほうが良いと思ったのでアップデートしました。たぶん上記のようなことをしなくても https://github.com/lambdalisue/vim-gista/commit/14425fb263f19789800040611a5bf464716556de で動くようになったはず・・・です。

ご確認お願いします

**Comment by hokorobi** [comment]
msys curl を使用しているのが原因でした。
mingw64 curl を使うことで問題を解消できました。

mingw64 curl インストールコマンド
pacman -S mingw-w64-x86_64-curl

インストールをしても環境変数 PATH を変更しないと msys curl を使うと思うので、
C:\msys64\usr\bin の前に C:\msys64\mingw64\bin; を加えました。

$ curl -V
curl 7.46.0 (x86_64-w64-mingw32) libcurl/7.46.0 OpenSSL/1.0.2e zlib/1.2.8 libidn/1.32 libssh2/1.6.0 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp
Features: IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz TLS-SRP

**Comment by lambdalisue** [comment]
@lambdalisue READMEかWikiにメモを残す

**Comment by toshi32tony3** [comment]
前回のコメントは一部間違っていたので、修正しています。

私の方でも+python, msysのcurlはpath通さずwgetのpathを通すでログインできることを確認しました。
ありがとうございました。

**Comment by hokorobi** [comment]
msys curl でも動作しました！

**Comment by hokorobi** [comment]
クローズしますが、Todo 的に残すなら再オープンしてください。

**Comment by lambdalisue** [comment]
;-)

**Comment by lambdalisue** [comment]
README に追加しました https://github.com/lambdalisue/vim-gista/blob/6391e539e105cad8b6deb8b985906be6b0723bc2/doc/vim-gista.txt#L641-L661

**Comment by hokorobi** [comment]
:+1:
