### ISSUE TITLE
:w で変更を保存できない

### ISSUE THREAD

**Issue by hokorobi** [lambdalisue/vim-gista#56]
:Gista list などから開いた gist を :w で保存できないようです。
:Gista patch なら保存できました。
調査方法があれば教えてください。

**Comment by lambdalisue** [comment]
再現しません… `:version` および `:autocmd BufWriteCmd` の結果を教えていただけると助かります。

**Comment by lambdalisue** [comment]
ただ関連するバグは見つけました、そっちを直してみます

**Comment by hokorobi** [comment]
ありがとうございます、更新できるようになりました。
