### ISSUE TITLE
:Gista login error

### ISSUE THREAD

**Issue by tyru** [lambdalisue/vim-gista#65]
`:Gista login` gave me the following error.
https://gist.github.com/tyru/1b6487b3538cac923107/4bac21fdc3b5fccc07cad2efbd22bf0903a8ef0b

But after #64 , `git config github.user` is not empty on my local machine,
so the above error does not occur now.
(Of cource, without any configuration (`:Gista login` succeeded, or `git config github.user` is not empty), the error should occur)

**Comment by lambdalisue** [comment]
Thanks. Now it show only the following line ;-)

```
ValidationError: An API username "" requires to follow "^[a-zA-Z0-9_-]+$"
```
