### ISSUE TITLE
Empty description on :Gista post causes an error

### ISSUE THREAD

**Issue by tyru** [lambdalisue/vim-gista#69]
I want to post quickly with even no description ;)

```
:Gista post
Please input a description of a gist:

function gista#command#command[26]..gista#command#post#command[35]..gista#command#post#call[8]..<SNR>265_interactive_description の処理中にエラーが検出されました:
行   13:
E118: 関数の引数が多過ぎます: gista#throw
```

https://gist.github.com/tyru/c1617d36ff5dfac88e91

**Comment by lambdalisue** [comment]
Fixed.

Btw, You can allow an empty description with `g:gista#command#post#allow_empty_description` or suppress interactive input with `g:gista#command#post#interactive_description` ;-)

**Comment by tyru** [comment]
Confirmed. Thanks!
Also confirmed the following setting!

```viml
let g:gista#command#post#allow_empty_description = 1
```
