### ISSUE TITLE
:Gista fork {URI}

### ISSUE THREAD

**Issue by tyru** [lambdalisue/vim-gista#72]
After I applied #71

`:Gista fork https://gist.github.com/davidosomething/d5522decdc324ea6bcf7` causes:

```
ValidationError: A gist ID "https://gist.github.com/davidosomething/d5522decdc324ea6bcf7" requires to follow "^w{,20}%(/w+)?$"
```

It would be happier if we can pass URI? :)

**Comment by lambdalisue** [comment]
`:Gista fork {gistid}` is a correct format. Try

```vim
:Gista fork d5522decdc324ea6bcf7
```

**Comment by lambdalisue** [comment]
> It would be happier if we can pass URI? :)

Hum... True but the basic mech was not designed for such usage.

**Comment by tyru** [comment]
> Hum... True but the basic mech was not designed for such usage.

OK, so please feel free to ignore this :)

**Comment by lambdalisue** [comment]
Ok. Thanks for understanding ;-)
