### ISSUE TITLE
Quickly yank (copy) a Gist's contents

### ISSUE THREAD

**Issue by sh78** [lambdalisue/vim-gista#83]
Would be great to directly yank the contents of a Gist right after  `:Gista list`. I want to use Gist like a snippet  manager. 

`yy` is already taken, but maybe `yi` for "yank inside" would fit. 

<img width="1225" alt="2018-05-12 at 17 23 59" src="https://user-images.githubusercontent.com/1066135/39962620-637bb644-5609-11e8-8f67-00b2c1e90d78.png">

**Comment by lambdalisue** [comment]
What do you expect if there are several files?

**Comment by sh78** [comment]
>
> What do you expect if there are several files?
>
Good point. I suppose it would be best to concatenate and yank all since
that would eliminate the scenario where a user has to reopen Gista to get
another file's contents. At least then they could easily just delete the
portion that they don't need.

Then again there could be two actions:

1. ‘yi‘ - yank inner contents of first file returned by gh API
2. ‘ya‘ - yank all files concatenated

These bindings correlate with vim's default motions, "in" and
"around/all".

>

**Comment by lambdalisue** [comment]
I feel it's a bit ambiguous. For example, assume that a gist have 4 files as

1. test.py
2. linux.txt
3. windows.txt 
4. mac.txt

and user want the content of windows.txt but don't know the order of appearance.

In this case, it's sometime difficult to distinguish the content and user can not determine which content comes from which.

So I don't feel the feature should be in gista itself.

For your purpose, the following simple macro would work I guess (not tested so some modification would be  required)

```
qa
<Return>
ggVG
"ay
<C-^>
<C-w>p
q
```

then press `@a`. Once you satisfy, write it to the buffer local function or whatever.

**Comment by sh78** [comment]
Fair enough - I didn't realize gists could have multiple files originally.

Thanks for typing up that macro @lambdaalisue! I'll make a key mapping for
my snippet management.
