### ISSUE TITLE
Posting an anonymous gist produces a 401 error from github

### ISSUE THREAD

**Issue by wimstefan** [lambdalisue/vim-gista#84]
When posting an anonymous gist with `:Gista -a post` I get the following error:
`vim-gista: 401: Unauthorized: Requires authentication
https://developer.github.com/v3/gists/#create-a-gist might help you resolve the error`

The same even happens after successfully logging in with `:Gista login`

**Comment by lambdalisue** [comment]
I haven't upgraded the docs but the anonymous gist feature has removed from gist itself.
https://blog.github.com/2018-02-18-deprecation-notice-removing-anonymous-gist-creation/

**Comment by wimstefan** [comment]
Fair enough. I completely missed that announcement ...
Thanks for informing me and also for that wonderful app!
